// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92mID_h2L9fOZP86_K_U7ae0jJMbHs8s',
    appId: '1:785103432861:web:b43a7a13f7890b7f10f874',
    messagingSenderId: '785103432861',
    projectId: 'raisoni-3da74',
    authDomain: 'raisoni-3da74.firebaseapp.com',
    storageBucket: 'raisoni-3da74.appspot.com',
    measurementId: 'G-YG0JPQQ6BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWYLzFW6lU-4Jb8iY11fmzt4QFpi4Cc5o',
    appId: '1:785103432861:android:67925e226288899010f874',
    messagingSenderId: '785103432861',
    projectId: 'raisoni-3da74',
    storageBucket: 'raisoni-3da74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgqn6enTt4R6Rl_qmD1MJK-fVBk-9B-0',
    appId: '1:785103432861:ios:06b39baf128b204410f874',
    messagingSenderId: '785103432861',
    projectId: 'raisoni-3da74',
    storageBucket: 'raisoni-3da74.appspot.com',
    iosClientId: '785103432861-rg5550vmmqhh5vpnc7r8hqlbvtt0hpan.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghrccstAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOgqn6enTt4R6Rl_qmD1MJK-fVBk-9B-0',
    appId: '1:785103432861:ios:06b39baf128b204410f874',
    messagingSenderId: '785103432861',
    projectId: 'raisoni-3da74',
    storageBucket: 'raisoni-3da74.appspot.com',
    iosClientId: '785103432861-rg5550vmmqhh5vpnc7r8hqlbvtt0hpan.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghrccstAttendanceApp',
  );
}
